/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import entidade.ETipoTreino;
import javax.swing.JOptionPane;
import negocio.NTipoTreino;

/**
 *
 * @author Bruno
 */
public class CadastroTreino extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroTreino
     */
    public CadastroTreino() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCodigoTreino = new javax.swing.JTextField();
        txtNomeclaturaTreino = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtADescricao = new javax.swing.JTextArea();
        bntConsultar = new javax.swing.JButton();
        bntSalvar = new javax.swing.JButton();
        bntExcluir = new javax.swing.JButton();
        bntLimpar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Cadastro de Treino");

        jLabel1.setText("Código de Treino");

        jLabel2.setText("Nomeclatura do Treino");

        jLabel3.setText("Descrição");

        txtCodigoTreino.setEditable(false);

        txtADescricao.setColumns(20);
        txtADescricao.setRows(5);
        jScrollPane1.setViewportView(txtADescricao);

        bntConsultar.setText("Consultar");
        bntConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntConsultarActionPerformed(evt);
            }
        });

        bntSalvar.setText("Salvar");
        bntSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSalvarActionPerformed(evt);
            }
        });

        bntExcluir.setText("Excluir");
        bntExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntExcluirActionPerformed(evt);
            }
        });

        bntLimpar.setText("Limpar");
        bntLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCodigoTreino, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bntConsultar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNomeclaturaTreino))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bntSalvar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bntExcluir)
                                        .addGap(55, 55, 55)
                                        .addComponent(bntLimpar))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigoTreino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntConsultar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNomeclaturaTreino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntSalvar)
                    .addComponent(bntExcluir)
                    .addComponent(bntLimpar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntConsultarActionPerformed
        // TODO add your handling code here:
        try {
                        
            String codigo = JOptionPane.showInputDialog("Digite o codigo do treino para consulta");
            
            if(codigo == null || codigo.isEmpty()){
                
                JOptionPane.showInputDialog("Digite o codigo do treino para consulta");
            }
            
            int intCodigo = Integer.parseInt(codigo);
            ETipoTreino treino = new NTipoTreino().consultar(intCodigo);
            
            if(treino.getCodigo_treino()!=0){
                preencherTela(treino);
            }
            else {
                JOptionPane.showMessageDialog(null,"Treino não cadastrado ou inexistente");
            }
            
            
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null,"Informe um codigo válido!");
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_bntConsultarActionPerformed

    private void bntLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntLimparActionPerformed
        // TODO add your handling code here:
        
        limparTela();
    }//GEN-LAST:event_bntLimparActionPerformed

    private void bntExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntExcluirActionPerformed
        // TODO add your handling code here:
        try {
             
            int confirma = (JOptionPane.showConfirmDialog(null,"Confirma a exclusão desse Treino ? , SysTrabson Training")
                + JOptionPane.YES_NO_OPTION);
            
            if(confirma == JOptionPane.YES_OPTION){
                int codigoTreino = Integer.parseInt(txtCodigoTreino.getText());
                new NTipoTreino().excluir(codigoTreino);
                
                JOptionPane.showMessageDialog(null, "Exclusão efetuada com sucesso");
                
                limparTela();
            }
            
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    }//GEN-LAST:event_bntExcluirActionPerformed

    private void bntSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSalvarActionPerformed
        // TODO add your handling code here:
        try {
            validarTela();
            
            ETipoTreino treino = new ETipoTreino();
            
            if(!txtCodigoTreino.getText().isEmpty()){
                treino.setCodigo_treino(Integer.parseInt(txtCodigoTreino.getText()));
            }
            
            treino.setNome_treino(txtNomeclaturaTreino.getText());
            treino.setDescricao(txtADescricao.getText());
            
            NTipoTreino nTreino = new NTipoTreino();
            nTreino.salvar(treino);
            
            limparTela();
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_bntSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntConsultar;
    private javax.swing.JButton bntExcluir;
    private javax.swing.JButton bntLimpar;
    private javax.swing.JButton bntSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtADescricao;
    private javax.swing.JTextField txtCodigoTreino;
    private javax.swing.JTextField txtNomeclaturaTreino;
    // End of variables declaration//GEN-END:variables

    public void validarTela()throws Exception{
        
         if(txtNomeclaturaTreino.getText().isEmpty()){
            throw new Exception("Insira o nome do Treino!");
        }
        if(txtADescricao.getText().isEmpty()){
             throw new Exception("Insira a descrição do Treino!");
        }
    }

    private void limparTela() {
        
        txtNomeclaturaTreino.setText("");
        txtADescricao.setText("");
    }

    private void preencherTela(ETipoTreino treino) {
        
        
        txtNomeclaturaTreino.setText(treino.getNome_treino()+ "");
        txtADescricao.setText(treino.getDescricao()+ "");
        bntExcluir.setEnabled(true);
    }


}

