/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import entidade.EAluno;
import entidade.ETipoTreino;
import javax.swing.JOptionPane;
import negocio.NAluno;
import negocio.NTipoTreino;
import util.ComboItem;

/**
 *
 * @author Bruno
 */
public class CadastroAlunos extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroAlunos
     */
    public CadastroAlunos() {
        initComponents();
        
        carregarCombo();
    }
    
    public CadastroAlunos(int codigo){
        this();
        try {
        
            EAluno aluno = new NAluno().consultar(codigo);
            
            preencherTela(aluno);
        
        
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtIdade = new javax.swing.JTextField();
        txtPeso = new javax.swing.JTextField();
        txtAltura = new javax.swing.JTextField();
        txtImc = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cmbTipoTreino = new javax.swing.JComboBox();
        bntConsultar = new javax.swing.JButton();
        bntSalvar = new javax.swing.JButton();
        bntExcluir = new javax.swing.JButton();
        bntLimpar = new javax.swing.JButton();
        txtSexo = new javax.swing.JTextField();
        txtBioTipo = new javax.swing.JTextField();
        bntIMC = new javax.swing.JButton();

        setClosable(true);
        setTitle("Cadastro de Alunos");

        jLabel1.setText("Código Aluno");

        jLabel2.setText("Nome");

        jLabel3.setText("Idade");

        jLabel4.setText("Peso");

        jLabel5.setText("Altura");

        jLabel6.setText("IMC");

        jLabel7.setText("Sexo");

        jLabel8.setText("Bio Tipo");

        txtCodigo.setEditable(false);

        txtPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesoActionPerformed(evt);
            }
        });

        txtImc.setEditable(false);

        jLabel9.setText("Tipo Treino");

        cmbTipoTreino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoTreinoActionPerformed(evt);
            }
        });

        bntConsultar.setText("Consultar");
        bntConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntConsultarActionPerformed(evt);
            }
        });

        bntSalvar.setText("Salvar");
        bntSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSalvarActionPerformed(evt);
            }
        });

        bntExcluir.setText("Excluir");
        bntExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntExcluirActionPerformed(evt);
            }
        });

        bntLimpar.setText("Limpar");
        bntLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntLimparActionPerformed(evt);
            }
        });

        bntIMC.setText("Calcular IMC");
        bntIMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntIMCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bntConsultar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(110, 110, 110)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel5)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtImc, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bntIMC))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBioTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(bntSalvar)
                                .addGap(18, 18, 18)
                                .addComponent(bntExcluir)
                                .addGap(18, 18, 18)
                                .addComponent(bntLimpar))
                            .addComponent(cmbTipoTreino, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntConsultar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bntIMC)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtImc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtBioTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cmbTipoTreino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntSalvar)
                    .addComponent(bntExcluir)
                    .addComponent(bntLimpar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesoActionPerformed

    private void cmbTipoTreinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoTreinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoTreinoActionPerformed

    private void bntSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSalvarActionPerformed
        // TODO add your handling code here:
        try {
            validaTela();
            
            EAluno aluno = new EAluno();

            if (!txtCodigo.getText().isEmpty()) {
                aluno.setCodigo_aluno(Integer.parseInt(txtCodigo.getText()));
            }
            
            aluno.setNome(txtNome.getText());
            aluno.setIdade(Integer.parseInt(txtIdade.getText()));
            aluno.setPeso(Double.parseDouble(txtPeso.getText()));  
            aluno.setAltura(Double.parseDouble(txtAltura.getText()));
            aluno.setImc(Double.parseDouble(txtImc.getText()));
            aluno.setSexo_aluno(txtSexo.getText());
            aluno.setBio_tipo(txtBioTipo.getText());
            String codigoTipo = ((ComboItem)cmbTipoTreino.getSelectedItem()).getCodigo_treino();
            aluno.getCodigo_tipo_treino().setCodigo_treino(Integer.parseInt(codigoTipo));
            
            NAluno nAluno = new NAluno();
            nAluno.salvar(aluno);
            
            JOptionPane.showMessageDialog(null ,"Operação Concluida com Sucesso");
            limparTela();
            
            
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    }//GEN-LAST:event_bntSalvarActionPerformed

    private void bntConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntConsultarActionPerformed
        // TODO add your handling code here:
        
        try {
            String codigo = JOptionPane.showInputDialog("Digite o codigo do aluno para a consulta : ");
            
            if(codigo == null || codigo.isEmpty()){
                JOptionPane.showInputDialog("Digite o codigo do aluno para a consulta : "); 
            }
            
            int intCodigo = Integer.parseInt(codigo);
            EAluno aluno = new NAluno().consultar(intCodigo);
            
            if(aluno.getCodigo_aluno()!=0){
                preencherTela(aluno);
            }
            else{
                JOptionPane.showMessageDialog(null,"Aluno não Cadastrado/Inexistente");
            }
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null,"Informe um codigo válido!");
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_bntConsultarActionPerformed

    private void bntExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntExcluirActionPerformed
        // TODO add your handling code here:
        try {
             
             int resposta = JOptionPane.showConfirmDialog(null,
                    "Confirma a exclusão do aluno ?", "SysTrabson Training",
                    JOptionPane.YES_NO_OPTION);
            if(resposta == JOptionPane.YES_OPTION){
                
                int codigoAluno = Integer.parseInt(txtCodigo.getText());
                new NAluno().excluir(codigoAluno);
                
                JOptionPane.showMessageDialog(null,"Operação concluída com sucesso");
                
                limparTela();
            }
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_bntExcluirActionPerformed

    private void bntLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntLimparActionPerformed
        // TODO add your handling code here:
        
        limparTela();
    }//GEN-LAST:event_bntLimparActionPerformed

    private void bntIMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntIMCActionPerformed
        // TODO add your handling code here:
        
        try {
            
            calcularIMC();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_bntIMCActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntConsultar;
    private javax.swing.JButton bntExcluir;
    private javax.swing.JButton bntIMC;
    private javax.swing.JButton bntLimpar;
    private javax.swing.JButton bntSalvar;
    private javax.swing.JComboBox cmbTipoTreino;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtBioTipo;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JTextField txtImc;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtSexo;
    // End of variables declaration//GEN-END:variables

    private void carregarCombo() {
        try {

            ComboItem item0 = new ComboItem("Selecione...", "0");
            cmbTipoTreino.addItem(item0);

            NTipoTreino treino = new NTipoTreino();

            for (ETipoTreino tipo : treino.listar()) {

                ComboItem item = new ComboItem(tipo.getDescricao(),
                        tipo.getCodigo_treino()+"");

                cmbTipoTreino.addItem(item);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
     
    private void limparTela() {
        
        txtNome.setText("");
        txtIdade.setText("");
        txtPeso.setText("");
        txtAltura.setText("");
        txtImc.setText("");
        txtSexo.setText("");
        txtBioTipo.setText("");
        cmbTipoTreino.setSelectedIndex(0);
    }
    
     private void preencherTela(EAluno aluno) {
        
        txtCodigo.setText(aluno.getCodigo_aluno()+ "");
        txtNome.setText(aluno.getNome()+ "");
        txtIdade.setText(aluno.getIdade()+"");
        txtPeso.setText(aluno.getPeso()+"");
        txtAltura.setText(aluno.getAltura()+"");
        txtImc.setText(aluno.getImc()+"");
        txtSexo.setText(aluno.getSexo_aluno()+"");
        txtBioTipo.setText(aluno.getBio_tipo()+"");
        
        int selecionado = 0 ;
        
        for (int i = 0; i < cmbTipoTreino.getModel().getSize(); i++) {
            
            ComboItem item = (ComboItem)cmbTipoTreino.getModel().getElementAt(i);
            
            if(aluno.getCodigo_tipo_treino().getDescricao().equals(item.getDescricao())){
                selecionado = i;
            }
        }
        
        cmbTipoTreino.setSelectedIndex(selecionado);
        bntExcluir.setEnabled(true);
    }
     
    public void validaTela()throws Exception{
        
         if(txtNome.getText().isEmpty()){
            throw new Exception("É necessário preencher o campo nome!");
        }
        if(txtIdade.getText().isEmpty()){
            throw new Exception("É necessário preencher o campo idade!");
        }
        if(txtPeso.getText().isEmpty()){
            throw new Exception("É necessário preencher o campo peso!");
        }
        if(txtAltura.getText().isEmpty()){
            throw new Exception("É necessário preencher o campo altura!");
        }
        if(txtImc.getText().isEmpty()){
            throw new Exception("É necessário preencher o campo IMC!");
        }
        if(txtSexo.getText().isEmpty()){
            throw new Exception("É necessário preencher o campo sexo!");
        }
        if(txtBioTipo.getText().isEmpty()){
            throw new Exception("É necessário preencher o campo biotipo!");
        }
        if(cmbTipoTreino.getSelectedIndex()== 0){
            throw new Exception("É necessário selecionar o tipo do treino!");
        }
        
    }

    private void calcularIMC() {
        
        try {
           double peso = Double.parseDouble(txtPeso.getText());
           double altura = Double.parseDouble(txtAltura.getText());
           
           float imc = (float) (peso/(Math.pow(altura,2)));
           
           txtImc.setText(imc+"");
           
           
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
        
    }
    
}
